export const FOUND_CURE = 'FOUND_CURE';
export const INITIATE_FOUND_CURE = 'INITIATE_FOUND_CURE';
export const LOAD_CURE_DETAILS = 'LOAD_CURE_DETAILS';
export const INITIATE_LOAD_CURE_DETAILS = 'INITIATE_LOAD_CURE_DETAILS';