export const FOUND_CURE = 'FOUND_CURE';

export const LOAD_CURE_DETAILS = 'LOAD_CURE_DETAILS';
export const INITIATE_LOAD_CURE_DETAILS = 'INITIATE_LOAD_CURE_DETAILS';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_START';
export const AUTH_FAIL = 'AUTH_START';